### ISSUE TITLE
[payments] Error with transfer RPC request to wallet daemon {"code":"ECONNRESET"}

### ISSUE THREAD

**Issue by danielbjornadal** [sumoprojects/sumokoin#29] opened 2017-10-03 16:30 UTC
Pool: https://github.com/billaue2/cryptonote-sumokoin-pool
Pool Config:
```
...
    "daemon": {
        "host": "10.42.8.83",
        "port": 19735
    },

    "wallet": {
        "host": "10.42.8.83",
        "port": 19734
    },
...
```
Pool Error: `[payments] Error with transfer RPC request to wallet daemon {"code":"ECONNRESET"}`

Daemon: https://github.com/sumoprojects/sumokoin
CMD: `/daemon/sumokoind --log-level=0 --p2p-bind-ip=0.0.0.0 --p2p-bind-port=19734 --rpc-bind-ip=0.0.0.0 --rpc-bind-port=19735 --data-dir=/daemon/data
`
Telnet OK from Pool to Daemon on Wallet port:
```
root@59fb45117d24:/usr/src/app/pool# telnet 10.42.8.83 19734
Trying 10.42.8.83...
Connected to 10.42.8.83.
Escape character is '^]'.
```

Both running on docker containers and communicating over a local docker network.
Is there any other security mechanism in the wallet that I have to consider when connecting remotely?

Complete Dockerfile:
```
FROM ubuntu:xenial

# Get needed packages
RUN apt-get update \
	&& apt-get install -y build-essential cmake libboost-all-dev libssl-dev pkg-config git g++ make libzmq3-dev

# Create app directory
RUN mkdir -p /daemon && mkdir -p /daemon/data && mkdir -p /daemon

# Install Daemon
WORKDIR /daemon/
RUN git clone https://github.com/sumoprojects/sumokoin.git src
WORKDIR /daemon/src/
RUN make -j 3

RUN mv /daemon/src/build/release/bin/* /daemon && rm -rf /daemon/src

ENV LOG_LEVEL 0
ENV P2P_BIND_IP 0.0.0.0
ENV P2P_BIND_PORT 19734
ENV RPC_BIND_IP 0.0.0.0
ENV RPC_BIND_PORT 19735
ENV DATA_DIR /daemon/data

EXPOSE 19734 19735

WORKDIR /daemon/
CMD /daemon/sumokoind --log-level=$LOG_LEVEL --p2p-bind-ip=$P2P_BIND_IP --p2p-bind-port=$P2P_BIND_PORT --rpc-bind-ip=$RPC_BIND_IP --rpc-bind-port=$RPC_BIND_PORT --data-dir=$DATA_DIR
```

Daemon netstats:
```
root@b903b67b4d9e:/daemon# netstat -luntp           
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:19734           0.0.0.0:*               LISTEN      12/sumokoind    
tcp        0      0 0.0.0.0:19735           0.0.0.0:*               LISTEN      12/sumokoind    
```

**Comment by haruto-tanno** [comment] 2017-10-04 03:39
I think the missing piece here was the wallet RPC daemon. Please run wallet RPC `sumo-wallet-rpc` daemon (from another docker if you like).

Daemon RPC ( `sumokoind`) is to provide pool with network info while wallet PRC (`sumo-wallet-rpc`) is for payments. Also, make sure you put correct wallet address (the same wallet to run RPC) to pool config file to receive/send mined coins.

**Comment by danielbjornadal** [comment] 2017-10-04 10:09
Thanks @haruto-tanno 
Could not find any guide that explained this. I had confused the P2P with the wallet RPC.

3 questions about the *-wallet-rpc:
Does the `poolServer.poolAddress` in the cryptonote-pool config.json have to be the same as used in the *-wallet-rpc?
Is there any documentation about sumo-wallet-rcp on creating/restoring wallet from a .json file?
is there any best practices on wallet keys and security when using automated start/boot on sumo-wallet-rpc?

**Comment by haruto-tanno** [comment] 2017-10-04 10:43
> Does the poolServer.poolAddress in the cryptonote-pool config.json have to be the same as used in the *-wallet-rpc?

Yes

> Is there any documentation about sumo-wallet-rcp on creating/restoring wallet from a .json file?

This will be a start https://repo.getmonero.org/monero-project/monero/commit/a2e378b91bf5d2a54284f8e20df5080f11d25ff6

But I don't see good reason to use it frequently.

> is there any best practices on wallet keys and security when using automated start/boot on sumo-wallet-rpc?

I'm not a security expert to give good advice for you but generally the wallet security is equal to your system security. So, login keys, user right separation, good firewall etc. would be highly recommended.

P/S: If you problem solved, pls close this issue. It's not a bug anyway.

**Closed** 2017-10-04 10:53 UTC
