### ISSUE TITLE
sumokoind high CPU Usage

### ISSUE THREAD

**Issue by BKdilse** [sumoprojects/sumokoin#77] opened 2018-02-20 21:08 UTC
I've complied Daemon from source, and have synched the blockchain fully.
My Server is running on high CPU Usage (73-100%), and it's the sumokoind process.

"Status" command shows:
Height: 103992/103992 (100.0%) on mainnet, not mining, net hash 19.26 MH/s, v2, update needed, 8+0 connections

Any ideas what may be causing this?

**Comment by sumogr** [comment] 2018-02-21 09:34
run sumokoin daemon with this flag --prep-blocks-threads 1 i.e.
./sumokoind --prep-blocks-threads 1

**Comment by BKdilse** [comment] 2018-02-21 10:42
Thanks @sumogr, that has made a difference.  Still runs high initially, then calms down.

**Comment by BKdilse** [comment] 2018-02-22 23:06
This is still causing issues.
I am now getting timeout errors from my nodejs-pool longRunner and blockManager modules.

Any further ideas?

**Comment by sumogr** [comment] 2018-02-23 07:38
I didnt know you were running a pool, you didnt mention it in your first post. Increase the number of threads on the flag. Try --prep-blocks-threads 3 (4 is default). If all else fails try a server with more cores

**Comment by BKdilse** [comment] 2018-02-23 07:45
Apologies, I should have mentioned it.  I've now reverted back to running it without the switch, and when I last looked, it was running a lot better.  I will try your suggestion if/when it falls over again.

Thanks

**Comment by BKdilse** [comment] 2018-03-07 11:47
Is anyone else experiencing performance issues?
What sort of hardware specs do you have?

**Comment by BKdilse** [comment] 2018-03-07 11:49
I have built 4 other coin pools and all of them are fine with the same spec. Xeon Quad Core E3-1225 V3, 4GB ram.

Sumo is the only one giving me problems.

Now I'm thinking of abandoning it.

**Comment by sumogr** [comment] 2018-03-07 11:50
Are they cryptonote coin pools? Ok, please close this issue

**Comment by BKdilse** [comment] 2018-03-07 11:52
Yes all cryptonote pools.

Why do you want  me to close this?

I'm just trying to understand what the hardware requirements are.  I be live hardware is sufficient.

**Comment by jpenner123** [comment] 2018-03-07 11:59
@BKdilse Generally speaking, for small pools, 2 vCPUs (Intel with AES support) should be enough. You should still close the issue as it only marginally relates to sumokoin daemon. Try a server with more CPU power (better CPUs, more cores, etc.). As far as your nodejs issues are concerned, they don't belong in this forum.

**Comment by BKdilse** [comment] 2018-03-07 12:03
@jpenner123 I have 1 miner on the Pool, and 4 cores with AES support.  I don't have issues with nodejs. I am questioning the daemon as that is hogging the cpu.

**Comment by sumogr** [comment] 2018-03-07 12:22
Try restarting your daemon with this flag this time --max-concurrency 1

**Comment by jpenner123** [comment] 2018-03-07 12:24
@BKdilse On my pool, the initial usage goes up for a few seconds, then goes down to 0.1% (also Intel AES Support). Once in a while I do see peeks that go way up but that is normal. Try using tools like iostat / strace in order to figure out what's going on on your system.

**Comment by BKdilse** [comment] 2018-03-07 12:30
@sumogr thanks, I'll try that setting.

@jpenner123 Mine does fluctuate, but mostly remains very high.  The pool UI therefor does not see block updates for ages, sometimes 45 minutes.

I'll try some more testing tonight.

**Comment by bobfeldbauer** [comment] 2018-03-08 10:21
@BKdilse Is it actually sumokoind causing your problem, or the wallet rpc? (I'm having issues with the wallet rpc blocking when running a pool, but haven't identified a cause yet.)

**Comment by BKdilse** [comment] 2018-03-08 10:52
@bobfeldbauer I believe it's the daemon and not wallet.  Api does not update quick enough.  I will spend more time over the weekend with the suggestions given.

**Comment by BKdilse** [comment] 2018-03-08 20:13
@sumogr I'm trying out --max-concurrency setting.  Do you know what if defaults to, without using this.  I have 4 cores, does it use 4 threads max, or does it have nothing to do with CPU cores?

**Comment by BKdilse** [comment] 2018-03-08 21:03
@sumogr @bobfeldbauer Guys, this is what I have found:
/usr/local/src/sumokoin/build/release/bin/sumokoind --rpc-bind-ip 0.0.0.0 --restricted-rpc --prep-blocks-threads 3 --max-concurrency 1

It's not the daemon on it's own casuing the issue, as CPU usage is low.  As soon as I start wallet RPC, the CPU shots up, and stays up.

No errors in the wallet logs.

**Comment by sumogr** [comment] 2018-03-08 21:49
have you compiled everything yourself? can you please try running everything with the compiled binaries? Lets try this approach

**Comment by BKdilse** [comment] 2018-03-08 21:53
@sumogr Yes, I compiled it myself, a few weeks ago.  I had to use the make release-static option due to SSL errors.  I am running the compiled libraries.

**Comment by sumogr** [comment] 2018-03-08 21:54
I am sure that it will run perfectly from the compiled binaries. The SSL errors you were getting were fixed with the last comits. If you dont want to run from the binaries try to recompile please.

**Comment by BKdilse** [comment] 2018-03-08 21:58
By "compiled binaries", I take it you are referring to the ones the devs have compiled?

OK, so at this moment, it's been running perfectly for the last 30 minutes.  I will leave it for a few days, and if/when problems re-occurs, I'll try to compiled with the latest source.  If that doesn't work, I'll try the compiled binaries.

Thanks, closing for now.

**Comment by bobfeldbauer** [comment] 2018-03-08 23:57
Implementing this would improve things, whether it directly fixes this specific issue or not. https://github.com/monero-project/monero/commit/935f74624928ddff8edf5bb32e68d3adfa91ef81

**Comment by BKdilse** [comment] 2018-03-11 09:52
Compiled latest version, and it's worse !!!
As soon as I start my sumo-wallet-rpc, the daemon dies with "Aborted (core dumped)"

I then downloaded the compiled version, which works, but has the same CPU hogging issue.

**Comment by sumogr** [comment] 2018-03-11 10:18
Devs confirmed that they are scanning the code to find the issue that throttles the cpu usage to a few users, as most likely this is a bug.
Can you try something in the meantime that may sound silly but most likely will provide a temporary solution till the fix? 
1. install cpulimit: **sudo apt-get -y install cpulimit**
2. Run **top** command and find the PID of the sumokoind
3. Run **sudo cpulimit --pid** (daemon PID) **--limit** (input an integer equal to the max percentage of cpu power you want the daemon to be consuming e.g 15)
Run the above on a screen and detach it in the background
Hope that gives a temporary solution till the fix

**Comment by BKdilse** [comment] 2018-03-11 16:11
I've given the server a reboot today, and it appears to be performing a little better.

btw, the overall CPU usage is 30-35%.  The sumokoind process is using up around 140%.

I'll give your suggestion a try when I see very bad performance.

**Comment by sumogr** [comment] 2018-03-11 18:07
ok. Leave the issue open

**Comment by rymdluo** [comment] 2018-03-12 21:47
I can confirm that a similar behavior is happening for me as well on E3-1270v5.

**Comment by sumogr** [comment] 2018-03-14 11:25
There is a pull, that is being tested atm before being merged, solving the high cpu usage (along with other things) if you cant wait or want to test it yourself before merging please compile from here
https://github.com/haruto-tanno/sumokoin

**Comment by BKdilse** [comment] 2018-03-20 17:12
I'll give that a go tonight.  Thanks @sumogr

**Comment by BKdilse** [comment] 2018-03-20 19:16
@sumogr Here are the results from the new compiled version:
1. Start Daemon, completed synching the last few blocks.
2. Start Nodejs Pool modules
3. CPU usage is acceptable now
4. Daemon crashes out "Aborte, core dumped".

Tried a few times, and had same issue.

Then I tried 3rd time, and when it crashed out, I simply restarted the daemon, and it is working so far.

Question is, what is causing it to dump core?

**Comment by BKdilse** [comment] 2018-03-20 19:47
I take that back, it's still crashing out, so it's actual worse than before, just isn't stable.  Any suggestions?

**Comment by quangvu3** [comment] 2018-03-21 04:19
Really strange, the official pool is running well with the latest code atm without any restrict. What's your OS? I suggest Ubuntu 16.04 and compile code clean:

`make clean && make release-static`

Of course, 4GB RAM is not ideal for running a pool but CPU should be fine.

**Comment by BKdilse** [comment] 2018-03-21 06:45
@quangvu3 OS is Ubuntu 16.04.4 LTS 64-bit.

Trying now with your suggestion.

**Comment by BKdilse** [comment] 2018-03-21 08:01
@quangvu3 That's working a lot better.  Not crashed, and low resource usage.  I have noticed something which is probably not related...  The daemon shows last block synched as **113095**, but my pools network stats show **113094** found an **hour** ago (same with various other pools).  Not noticed that much delay previously.  Any thoughts?

**Comment by BKdilse** [comment] 2018-03-21 08:03
Latest Daemon update has fixed the performance issue, thanks to all involved in this.  :)

**Comment by BKdilse** [comment] 2018-03-22 20:34
Few days running, and the issue is back.
Ubuntu top shows this:   CPU147.7% MEM 57.6%   process sumokoind

Any further suggestions?

**Comment by VirtuBox** [comment] 2018-03-25 01:45
Hello, 

I have a similar issue with sumokoind CPU usage. I'm also running other cryptonote coin daemon without the same high-cpu usage. And Sumokoin Pool hashrate isn't high (only 1KH/s).

![sumokoind cpu usage](https://img.virtubox.net/images/2018/03/25/Screenshot_242.png)

**Comment by rymdluo** [comment] 2018-03-26 19:37
I can also confirm (again) the same high CPU usage.

**Comment by quangvu3** [comment] 2018-04-06 04:29
Can anyone confirm the issue after upgrading binaries to v0.3.0.0 (Aomori)?

**Comment by BKdilse** [comment] 2018-04-06 06:33
Yes. I can.  Same issue.  Out of all my 10 coin pools, sumo is the highest cpu usage pool.

**Comment by quangvu3** [comment] 2018-04-06 11:41
While it may be understandable that Sumokoin daemon may consume a little more CPU than others (due to larger RingCT size), it has never been a problem at official pool. Here is a screenshot from `top` command:

![cmae0hn_x5jwwcaoyfcp83k4q42ek2ydowp4xtrqjpb_8nmn1bxh6ngt-isrqdto3s2ezwn6vvkcsjrcjyo1tn0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/195045/38419249-dc20bccc-39c9-11e8-9e03-f9c8eea2293d.png)

**Comment by BKdilse** [comment] 2018-04-06 12:13
What hardware is it running on?

**Closed** 2018-04-12 09:42 UTC
